name: PR-CI

on:
  pull_request:
    branches: '**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: check permissions
        run: ls -l node_modules/.bin

      - name: list files
        run: ls -la

      - name: Upload node_modules_artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  verify-code-formatting:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules

      - name: check permissions
        run: ls -l node_modules/.bin

      - name: grant permissions
        run: chmod +x node_modules/.bin/*

      - name: grant package.json permissions
        run: chmod +x package.json

      - name: check permissions
        run: ls -l node_modules/.bin

      - name: list files
        run: ls -la

      - name: test prettier
        run: yarn prettier:ci

      - name: test eslint
        run: yarn lint

  run-tests:
    needs: [install-dependencies, verify-code-formatting]
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules

      - name: unit test
        run: yarn test

      - name: e2e tests
        run: yarn e2e:ci
