name: PR-CI

on:
  pull_request:
    branches: '**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules

  verify-code-formatting:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - uses: actions/checkout@v4

      - name: use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules

      - name: list files
        run: ls -la node_modules

      - name: read prettier package.json
        run: cat node_modules/prettier/package.json

      # - name: test prettier
      #   run: yarn prettier:ci

      - name: test eslint
        run: yarn lint

  run-tests:
    needs: [install-dependencies, verify-code-formatting]
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - uses: actions/checkout@v4

      - name: use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules

      - name: unit test
        run: yarn test

      - name: e2e tests
        run: yarn e2e:ci
