name: Production

on:
  push:
    branches:
      - 'test'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: Tar node_modules directory
        run: tar czf node_modules.tar.gz -C node_modules .

      - name: Upload node_modules_artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.tar.gz

  run-unit-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    container: node:18-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: Extract node_modules
        run: mkdir node_modules && tar xzf node_modules.tar.gz -C ./node_modules

      - name: unit test
        run: yarn test

  run-e2e-tests:
    needs: [install-dependencies, run-unit-tests]
    runs-on: ubuntu-latest
    container: cypress/base:20.11.0

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: Extract node_modules
        run: mkdir node_modules && tar xzf node_modules.tar.gz -C ./node_modules

      - name: install cypress
        run: yarn add cypress

      - name: e2e tests
        run: yarn e2e:ci

  release:
    needs: [install-dependencies, run-unit-tests, run-e2e-tests]
    runs-on: ubuntu-latest

    env:
      image_tag: ${{vars.DOCKER_IMAGE_OWNER}}/kiosk-ui-production:${GITHUB_SHA}
      image_latest: ${{vars.DOCKER_IMAGE_OWNER}}/kiosk-ui-production:latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Images
        run: |
          docker build -t ${{ env.image_tag }} .
          docker tag ${{ env.image_tag }} ${{ env.image_latest }}

      - name: Push Docker Images
        run: |
          docker push ${{ env.image_tag }}
          docker push ${{ env.image_latest }}

  deploy:
    needs: [install-dependencies, run-unit-tests, run-e2e-tests, release]
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy webhook
        run: curl --request POST '${{ secrets.DEPLOY_KIOSK_UI_PRODUCTION_WEBHOOK }}'
